### PR TITLE
Properly label form inputs and restore focus style

### PR DESCRIPTION
**Pull request by nickendle**
Fixes https://www.pivotaltracker.com/story/show/169743515

### CODE REVIEW

**Comment by nickendle** [comment]
@hwinn4 good points! I pushed an update that makes a bit more sense, using the fieldset tag and removing the list items. I'm thinking that the legend tag won't really be necessary here since it's a pretty self-contained form that's the only thing on the page- and Contact is mentioned in the page title.

**Comment by hwinn4** [comment]
@nickendle Noice! One question-- is it possible to use `<div>` tags instead of the `<p>`? If it's an easy lift, I think divs are the better semantic choice here since the content of the <p> tag isn't really a paragraph.

**Comment by nickendle** [comment]
@hwinn4 In this specific case I think they can be used interchangeably, 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p states that 

> HTML paragraphs can be any structural grouping of related content, such as images or form fields

and they use `<p>` in the form examples as well. https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form

i think either way is fine, if there's strong feelings i can change it.

**Comment by hwinn4** [comment]
@nickendle Thanks for the examples! Leaving it works for me :) TMYK 👍

**Pull request merged**
